# Generated by Django 3.1.2 on 2021-01-27 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cateogies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('thumbnail', models.ImageField(upload_to='photos')),
                ('description', models.TextField(max_length=300)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=300)),
                ('acess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cateogies')),
            ],
        ),
    ]
