# Generated by Django 3.1.2 on 2021-01-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateogies',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
